export const LOAD_ERROR_DATA = 'LOAD_ERROR_DATA';
export const  LOAD_DATA_PROCESS = 'LOAD_DATA_PROCESS';
export const LOAD_DATA_DONE = 'LOAD_DATA_DONE';
export const SAVE_CORRECT_TASK = 'SAVE_CORRECT_TASK';
